// <auto-generated />
using System;
using JobsGeParser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobsGeParser.Data.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20260707205939_AddScrapeBatchId")]
    partial class AddScrapeBatchId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobsGeParser.Data.CategoryEntity", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ListUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("JobsGeParser.Data.JobCategoryEntity", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("CategorySlug")
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobId", "CategorySlug");

                    b.HasIndex("CategorySlug");

                    b.ToTable("job_categories", (string)null);
                });

            modelBuilder.Entity("JobsGeParser.Data.JobEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CompanyLink")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("Published")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("JobsGeParser.Data.ScrapeRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CategorySlug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("Failed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer");

                    b.Property<int>("Skipped")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Updated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("CategorySlug", "StartedAt");

                    b.ToTable("scrape_runs", (string)null);
                });

            modelBuilder.Entity("JobsGeParser.Data.JobCategoryEntity", b =>
                {
                    b.HasOne("JobsGeParser.Data.CategoryEntity", "Category")
                        .WithMany("JobCategories")
                        .HasForeignKey("CategorySlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobsGeParser.Data.JobEntity", "Job")
                        .WithMany("JobCategories")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobsGeParser.Data.ScrapeRunEntity", b =>
                {
                    b.HasOne("JobsGeParser.Data.CategoryEntity", "Category")
                        .WithMany("ScrapeRuns")
                        .HasForeignKey("CategorySlug")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JobsGeParser.Data.CategoryEntity", b =>
                {
                    b.Navigation("JobCategories");

                    b.Navigation("ScrapeRuns");
                });

            modelBuilder.Entity("JobsGeParser.Data.JobEntity", b =>
                {
                    b.Navigation("JobCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
